# Generated by Django 2.2.6 on 2019-10-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='rotation',
        ),
    ]
