# Generated by Django 2.2.6 on 2019-10-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_remove_artwork_rotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='landscape',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='portrait',
        ),
    ]
