# Generated by Django 2.2.6 on 2019-10-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_auto_20191026_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='photo',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
