# Generated by Django 2.2.6 on 2019-10-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_auto_20191026_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='landscape',
            field=models.ImageField(null=True, upload_to='artworks'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='portrait',
            field=models.ImageField(null=True, upload_to='artworks'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='photo',
            field=models.ImageField(upload_to='artworks'),
        ),
    ]
