# Generated by Django 2.2.6 on 2019-10-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_auto_20191026_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='landscape',
            field=models.FileField(null=True, upload_to='artworks'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='portrait',
            field=models.FileField(null=True, upload_to='artworks'),
        ),
    ]
