# Generated by Django 2.2.6 on 2019-10-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_auto_20191026_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='landscape',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='portrait',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
